--- # VARIABLE AT A COMMAND LINE PASSING EXAMPLE
- hosts: "{{ hosts }}"
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install some software
    yum: pkg={{ pkg }} state=latest
