--- # My First YML Playbook for Ansible
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefault.yml
  vars_prompt:
    - name: web_domain
      prompt: Web_Domain
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
    - name: Install the Lynx Web Browser
      action: yum name={{ pkg_version }} state=installed
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
