--- # The Pause Module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
   - name: Install HTTPD
     action: yum name=httpd state=installed
   - name: Pausing
     pause:
       prompt: "Make sure the installation in complete..."
   - name: Verify lynx installation
     action: yum name=lynx state=installed
